### ISSUE TITLE
"Subscribe to our newsletter" in the footer needs to become a subscription to new blog posts

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#102]
This is part of a slightly bigger question of how to handle the blog at all at all.

Assuming we're sticking to WP for now, then let's get this same signup form (Mailchimp?) collecting emails from the blog page and set it that we email that group of people when there's a new blog post.

Quite possibly there's a WP plugin to handle all of this?

**Comment by affan00** [comment]
@marcoherbst...there are some plugins that might be useful.
1- "E-Mail subscriber WP plugin". https://wordpress.org/plugins/email-subscribers/
Advantages:
i..     Send notification email to subscribers when new posts are published to your blog.
ii.     Create a HTML newsletter and send manually (Or Schedule) to subscribers.
iii.    Auto generate a newsletter with latest available posts in the blog and send to your subscribers via          cron job.
iv.   Send notification email to subscribers when new posts are published.
v.    Automatic welcome mail to subscriber (Optional).
vi.   Import/Export subscriber emails.
vii.  HTML editor to compose newsletter.
viii. Send newsletter.
ix.  Sent mail status and when it was viewed

2- "The Newsletter Plugin " https://wordpress.org/plugins/newsletter/
Advantages:
i.. Unlimited Subscribers with statistics
ii. Unlimited Emails with tracking
iii. Customizable subscription widget, page or custom form
iv. WordPress User Registration seamless integration
v. Subscribers preferences to fine-target your campaigns
vi. Html and Text versions of Emails
vii. All messages are fully translatable from Admin Panel (no .po/.mo)
viii. Diagnostics Panel to check your blog mailing capability

**Comment by marcoherbst** [comment]
We scrapped this anyhow. Closing.
