### ISSUE TITLE
We still seem to be getting comments in the admin area even though they are disabled

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#103]
This seems fixable , there is some chat about it:
https://wordpress.org/support/topic/a-disable-comments-setting-entirely-permanently

M

**Comment by affan00** [comment]
@marcoherbst seems that issue resolved. Let me know if spam bots receive again.

**Comment by affan00** [comment]
@marcoherbst disable comments by editing them and unchecking "Comments" in the Discussion field below the editor.

**Comment by affan00** [comment]
checked again but no spam bots received again. seems issue resolved.
