### ISSUE TITLE
Update http://www.evercam.io/team

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#104]

**Comment by affan00** [comment]
@marcoherbst ... What things you need to update in http://www.evercam.io/team??

**Comment by marcoherbst** [comment]
Include Affan, Muneeb, Faisal

:)

m

On 21 October 2015 at 11:00, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> ... What things you need to
> update in http://www.evercam.io/team??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/104#issuecomment-149843355>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
oki :)

**Comment by affan00** [comment]
team updated and deployed successfully.
