### ISSUE TITLE
Image on snapmail, cloud storage, timelapse is not visible (in opera browser) but visible in chrome.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-public-site#109]
![screenshot_2015-10-21-14-34-09](https://cloud.githubusercontent.com/assets/14149453/10633213/c4c6df56-7802-11e5-8bd0-5fecfaf72a82.png)
![screenshot_2015-10-21-14-34-31](https://cloud.githubusercontent.com/assets/14149453/10633214/c4d0b878-7802-11e5-95fa-0b9022f36d5c.png)

**Comment by marcoherbst** [comment]
Can you work out why this is happening and propose a fix?

m

On 21 October 2015 at 10:48, Affan Qureshi <notifications@github.com> wrote:

> [image: screenshot_2015-10-21-14-34-09]
> <https://cloud.githubusercontent.com/assets/14149453/10633213/c4c6df56-7802-11e5-8bd0-5fecfaf72a82.png>
> [image: screenshot_2015-10-21-14-34-31]
> <https://cloud.githubusercontent.com/assets/14149453/10633214/c4d0b878-7802-11e5-95fa-0b9022f36d5c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/109>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst  some versions of opera mini doesn't support font icons and instead of image it shows rectangle symbol.

**Comment by affan00** [comment]
@marcoherbst recent screenshoot on other version of opera.
![screenshot_2015-10-26-13-11-55](https://cloud.githubusercontent.com/assets/14149453/10724393/118b28b0-7be6-11e5-9d51-2f75eebfe1b1.png)

**Comment by affan00** [comment]
no issue found on different browsers and other version of opera.
