### ISSUE TITLE
In "Add your camera" session snap of camera  in step1 is not visible properly in opera browser but visible in chrome. 

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-public-site#110]
![screenshot_2015-10-21-14-43-16](https://cloud.githubusercontent.com/assets/14149453/10633245/eb101e3e-7802-11e5-872f-a0a1090ff4df.png)

**Comment by marcoherbst** [comment]
Well spotted. Are you able to work out why this is happening? Give some explanation?

**Comment by affan00** [comment]
@marcoherbst  this issue is in that version of opera mini browser. i check in other version of opera than  images are properly visible.

**Comment by affan00** [comment]
@marcoherbst  recent screenshoot on other version of opera
![screenshot_2015-10-26-13-12-06](https://cloud.githubusercontent.com/assets/14149453/10724445/75473bbe-7be6-11e5-97a0-8a1115502653.png)

**Comment by affan00** [comment]
no issue found on different browsers and other version of opera.
