### ISSUE TITLE
In "Requires Authentication" hints (create username, camera password) should be in light gray color like "http:// hint (external ip/URL)

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-public-site#111]
![screenshot_2015-10-21-14-35-13](https://cloud.githubusercontent.com/assets/14149453/10633289/2628a6b2-7803-11e5-97f1-67d13c05b7e3.png)

**Comment by marcoherbst** [comment]
well spotted.

**Comment by affan00** [comment]
@marcoherbst recent screenshoot on other version of operamini
![screenshot_2015-10-26-13-12-14](https://cloud.githubusercontent.com/assets/14149453/10724418/45abf0f2-7be6-11e5-9ad7-f27c62b4ee76.png)

**Comment by affan00** [comment]
no issue found on different browsers and other version of opera.
