### ISSUE TITLE
/public/cameras/ ... when I zoom out to see the world, it will randomly zoom me in again ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#115]
....using chrome

**Comment by affan00** [comment]
@marcoherbst checked in chrome but it's seems fine. using '+' and '-' sign and also from mouse wheel but its working properly.

**Comment by marcoherbst** [comment]
hmmm.... try again. And if you can't repeat it, try on a Windows PC.
M

**Comment by affan00** [comment]
@marcoherbst ... yes, got it. Tried on window pc It's zoom in again when try to zoom out.

**Comment by marcoherbst** [comment]
@affan00  ... will you be able to tackle this? Or should we reassign it?

**Comment by affan00** [comment]
I can do it Marco. If i need some help i will coordinate with Mr Azhar.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
fixed the issue related to zoom in. now it's working fine.

**Comment by marcoherbst** [comment]
Nice one.

**Comment by affan00** [comment]
it's done.
