### ISSUE TITLE
Creation of evercam.io/features

### ISSUE THREAD

**Issue by rossom** [evercam/evercam-public-site#124]
Hi,

See jpgs "slide 1-3" for direction. 

![slide1](https://cloud.githubusercontent.com/assets/4725787/11070989/5fdee19a-87d6-11e5-9378-1d44a830893d.JPG)
![slide2](https://cloud.githubusercontent.com/assets/4725787/11070991/5fe6eb74-87d6-11e5-9aaf-c4db1400a4be.JPG)
![slide3](https://cloud.githubusercontent.com/assets/4725787/11070990/5fe69ade-87d6-11e5-9d0f-9c5e468d8d1d.JPG)

The other jpg files have high res copies of the design.

The psd's contain layered images if required.

The png's are for the mobile site.

![download-ios](https://cloud.githubusercontent.com/assets/4725787/11070865/93b39b74-87d5-11e5-8d1c-70b74fd48e70.png)
![download-android](https://cloud.githubusercontent.com/assets/4725787/11070867/93b7393c-87d5-11e5-878d-638eff733e01.png)
![features-photoshopped copy](https://cloud.githubusercontent.com/assets/4725787/11070866/93b6f33c-87d5-11e5-95a1-25070d5f72a5.jpg)
![features-photoshopped-mobile copy](https://cloud.githubusercontent.com/assets/4725787/11070868/93cc0592-87d5-11e5-83ed-83593288b3d9.jpg)

**Comment by rossom** [comment]
@marcoherbst

**Comment by marcoherbst** [comment]
Nice one. @affan00 , we'll be discussing this soon. :)

**Comment by rossom** [comment]
For when you're working on this page: It is intended that the mac at the top of the page will host a video file.

I was originally thinking animated gif, but there are quality and file sizes issues with these.

I've been tinkering around with html5 video. 

Could this be as easy as my supplying a .webm file type?

**Comment by affan00** [comment]
@marcoherbst created a new page features. http://www.evercam.io/features
