### ISSUE TITLE
Improve Public Camera page for mobile

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-public-site#134]
1. On smaller screen, there is a huge blank gap between camera view and camera details for RTSP cameras, see screenshot:
<img width="397" alt="screen shot 2015-12-18 at 15 20 06" src="https://cloud.githubusercontent.com/assets/5046761/11900113/95d62e24-a59b-11e5-958e-525f694e0b28.png">

2. The 'Add' button on the right top disappears for RTSP cameras on Android WebView (eg, Stephen Green camera), but it works in Chrome.
![screenshot_20151218-153226](https://cloud.githubusercontent.com/assets/5046761/11900269/b883c73c-a59c-11e5-899f-812a28e4a348.png)

**Comment by affan00** [comment]
@ijunaidfarooq  issues is coming from widget itself, and issue can be fix with the use of jquery.

**Comment by ijunaidfarooq** [comment]
@affan00 :+1:

**Comment by affan00** [comment]
@liutingdu issue resolved.

**Comment by liutingdu** [comment]
@affan00 Sorry for testing this late.. 

Now I see the gap is gone, but the right top corner add button '+' is still not visible in Android screen (It's visible when I test it in Chrome, if you can't reproduce it please let me know and I can help inspect it with Android emulator), see  this screenshot:
![noaddbutton](https://cloud.githubusercontent.com/assets/5046761/12389543/5b633c3e-bdd1-11e5-9c8b-4ad4c9349c29.png)

It seems all cameras are in JPG view now, did we disable RTSP for public cameras?

One more problem: When I choose a camera on mobile screen, before the JPG view start moving, the thumbnail doesn't seem to be responsive, the image doesn't fit screen width (This can be reproduced on both Android webview and PC Chrome). See screenshot. Is it fixable?
![notresponsive](https://cloud.githubusercontent.com/assets/5046761/12389627/d15d2c88-bdd1-11e5-963e-5e1ff7f9d52d.png)

**Comment by marcoherbst** [comment]
rtsp is disabled across all of evercam.

I guess in the next week or 2 @mosic will bring it back to life, when a few
other things have settled down.

m

On 18 January 2016 at 10:59, Liuting Du <notifications@github.com> wrote:

> @affan00 <https://github.com/affan00> Sorry for testing this late..
>
> Now I see the gap is gone, but the right top corner add button '+' is
> still not visible in Android screen (It's visible when I test it in Chrome,
> if you can't reproduce it please let me know and I can help inspect it with
> Android emulator), see this screenshot:
> [image: noaddbutton]
> <https://cloud.githubusercontent.com/assets/5046761/12389543/5b633c3e-bdd1-11e5-9c8b-4ad4c9349c29.png>
>
> It seems all cameras are in JPG view now, did we disable RTSP for public
> cameras?
>
> One more problem: When I choose a camera on mobile screen, before the JPG
> view start moving, the thumbnail doesn't seem to be responsive, the image
> doesn't fit screen width (This can be reproduced on both Android webview
> and PC Chrome). See screenshot. Is it fixable?
> [image: notresponsive]
> <https://cloud.githubusercontent.com/assets/5046761/12389627/d15d2c88-bdd1-11e5-963e-5e1ff7f9d52d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/134#issuecomment-172497544>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@liutingdu when rtsp will be enable i will fix this ASAP.

**Comment by liutingdu** [comment]
@affan00 The issue is nothing to do with RTSP :) 

Please check the screenshots, the problems are 
1. The 'Add' button is not showing up and 
2. The thumbnail image is not responsive

**Comment by affan00** [comment]
@liutingdu thanks for your cooperation. the plus icon is disappeared after adding camera to your account or for already added cameras. It's fixed.

**Comment by liutingdu** [comment]
:+1: Thanks!
