### ISSUE TITLE
Test snapshot doesn't work

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-public-site#137]
In add camera form, after filling in correct camera details and hit 'Check for snapshot', it always fails. Could be related to the media.evercam.io URL change?

**Comment by liutingdu** [comment]
This bug is only happening for me on the public site. It works on dashboard :)

**Comment by affan00** [comment]
@marcoherbst @liutingdu our test snapshot is not working because in our add camera widget the endpoint change from api to media. just need to replace api with media. And it can be change from dashboard.

**Comment by liutingdu** [comment]
@affan00 Is it done? It still doesn't work. Or are you saying it's a dashboard issue and I should report it again in the dashboard repo?

**Comment by affan00** [comment]
Liuting I already report it in dashboard and also muneeb fix it but not
deployed, that's why it still not work. Waiting for muneeb to deploy
changes so that we can see the results. :)

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by liutingdu** [comment]
@affan00 :+1:  Thanks

**Comment by affan00** [comment]
Successfully deployed. Now it's working fine.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by liutingdu** [comment]
Hi @affan00, I just tried it again but still doesn't work. Can you confirm it's working for the public site: http://www.evercam.io/ ?

**Comment by affan00** [comment]
Hi2 Liuting Du. I confirmed, yes it's working fine on evercam public site.
http://www.evercam.io/
see attachment,recently i checked it.

[image: Inline images 1]

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by liutingdu** [comment]
@affan00 The only difference is I was testing on a camera that requires authentication. Can you try a camera with username & password see if it works too?

**Comment by liutingdu** [comment]
@affan00 Oh now it works! I guess the reason it failed was I forgot to refresh the page.... Thanks!

**Comment by affan00** [comment]
its ok. welcome.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani
