### ISSUE TITLE
Vendor / Model Pages improvements.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#138]
@affan00  list here the pages that are built, but not linked to on the live site:
e.g.: http://www.evercam.io/vendors2

Then we'll work out what we actually want.

Also, change this page to show all vendors and remove pagination.

**Comment by affan00** [comment]
list of new built pages.
1. http://www.evercam.io/features.
2. http://www.evercam.io/models2.
3. http://www.evercam.io/vendors2

**Comment by affan00** [comment]
Remove the pagination from the vendors2 page. http://www.evercam.io/vendors2

**Comment by affan00** [comment]
done all the changes with vendors and models page and make it live.
