### ISSUE TITLE
Index2 Page - items 8 & 9

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#139]
1.  Mobile apps.
2.  Any camera or device.
(3. Public Cameras)

**Comment by marcoherbst** [comment]
Mobile Apps - for the icon, use the 2 app store images.
Text: Beautiful  Apps for iOS or Android (make iOS & Android into hyperlinks).

Any Camera - try to find an icon.
Text: Works with any IP Camera.

@affan00 thanks. (NB - No changes needed on features page).

**Comment by affan00** [comment]
after making changes in index2 page. https://www.evercam.io/index2. Does it
seems ok?
I am still searching for 2 app-store icon as soon as i get the more
suitable icon i will change Mobile app fa icon.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
it's done and live now.
