### ISSUE TITLE
Create a page /cloud-cctv

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#144]
Make it a simple page with this content:

https://evercam.io/features#cloudstorage   (and also text from next section: Long Term Archive on the same page)

We will soon be redirecting cloud.camba.tv to this page as cloud.camba.tv has very good SEO.

**Comment by affan00** [comment]
Here is the link of cloud-cctv page.  https://evercam.io/cloud-cctv.

**Comment by affan00** [comment]
It's done
