### ISSUE TITLE
Vendor / models ...

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-public-site#15]
- [ ] Use the suitable metadata, Title and description.
- [ ] Add an "Add this camera" to Evercam button.

Was very impressed with the second result, inline results.

![screenshot 2016-05-06 22 25 39](https://cloud.githubusercontent.com/assets/5648894/15086566/9b3e7572-13d9-11e6-834d-6ae5c71be567.png)

**Comment by affan00** [comment]
done

**Comment by marcoherbst** [comment]
Moved to Dash
