### ISSUE TITLE
Basic SEO fixes (urgent)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#158]
I got this simple report from a company, most of which seems to be true.

Hopefully we could tackle the basics as a matter of importance (this week pls).

- [x] Not proper use of Title
- [x] Lengthy Description & also not Optimized.
- [x] Improper use of keywords.
- [x] Robots.txt file is missing.
- [x] Not proper use of H1 Tags in Title

**Comment by affan00** [comment]
done
