### ISSUE TITLE
Public Cameras aren't showing up on evercam/public/cameras

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-public-site#16]
1. Find a camera on dashboard with no location
2. Add location to that camera and the camera was public but after adding the location it didn't show up on https://evercam.io/public/cameras/ map.

**Comment by marcoherbst** [comment]
I think they are working now, but you can double check please.

**Comment by affan00** [comment]
Tested with 5 cameras. It's working fine, Unable to replicate the issue so I am closing this issue.
