### ISSUE TITLE
Public camera page looks broken because of missing cluster icons

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-public-site#161]
Looks like the cluster markers were moved from the url that the page was using, see screenshot.

![image](https://cloud.githubusercontent.com/assets/1229422/17042449/e0c0ab64-4fad-11e6-9ec8-749d65c44b83.png)

**Comment by affan00** [comment]
it's fixed now.

**Comment by affan00** [comment]
this was due to google has moved their utility library from google code to github and our image urls was pointed to their old library.

**Comment by mosic** [comment]
@affan00 Ok, great. But why isn't that change (and all other changes on the public website) in this repo now? The last update was done in December 2015.

**Comment by affan00** [comment]
@mosic I will update this changes and all other changes later right now I did that changes online.
