### ISSUE TITLE
Pagespeed optimisations

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#36]
https://developers.google.com/speed/pagespeed/insights/?url=evercam.io&tab=desktop

Certainly the top ones. 

Seems to me that things like bitnami, comments, and forms JS files are not needed. Are they?

![image](https://cloud.githubusercontent.com/assets/5648894/18755633/e0a3fe98-80e4-11e6-9459-7088f0c70d41.png)

**Comment by affan00** [comment]
It's done. Will review it again after few weeks.
