### ISSUE TITLE
Internal links, in footer for example, are missing the trailing /

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#37]
In footer it's https://evercam.io/team 
but that just redirects to https://evercam.io/team/

Either we change the footer or we change how we use the trailing /

I would prefer to not use the trailing / , but I guess there is some good reason why you are doing it ... so, if it isn't easy to revert to the non-trailing slash https://evercam.io/team  , then your task is to fix all the internal links.

Please be careful on this task.

**Comment by affan00** [comment]
Removed the trailing / at the end of the URL. closing this now.
