### ISSUE TITLE
Daniel Caffrey twitter links to Marco Herbst instead

### ISSUE THREAD

**Issue by jxs** [evercam/evercam-public-site#66]
while browsing the team page, noticed Daniel Caffrey twitter links to Marco Herbst instead
[here](https://github.com/evercam/evercam-public-site/blob/master/team.php#L146)

cheers :)

**Comment by marcoherbst** [comment]
Thanks @jxs  ... @shakeelanjum , will you sort it out. @scandox is his Twitter handle.
M
