### ISSUE TITLE
Add mixpanel logo to footer

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#85]
https://mixpanel.com/free/

@shakeelanjum  could you do this please?

Tks.

M

**Comment by shakeelanjum** [comment]
Added and verified.

**Comment by marcoherbst** [comment]
Tks.

On 29 July 2015 at 13:23, M. Shakeel Anjum <notifications@github.com> wrote:

> Closed #85 <https://github.com/evercam/evercam-public-site/issues/85>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/85#event-368266630>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
