### ISSUE TITLE
Public cameras UI problems

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-public-site#88]
![screen shot 2015-08-11 at 10 25 00-1439285428915](https://cloud.githubusercontent.com/assets/5046761/9196169/8a957a50-4020-11e5-9411-7974d5f632ec.png)

1. Two scroll bars
2. Unnecessary divider
3. Space between texts
4. Too much space

**Comment by affan00** [comment]
@marcoherbst 1) checked in different browsers only one scroll bar is shown. 
![camera](https://cloud.githubusercontent.com/assets/14149453/10781756/e5661dee-7d6b-11e5-962d-abf108234ad0.png)

**Comment by liutingdu** [comment]
@affan00 

I am able to reproduce it by dragging to make the browser narrower (until the camera list is hidden) and then drag back to normal size (with Chrome)

**Comment by affan00** [comment]
@liutingdu i also tried same but no issue found on my side using chrome on ubuntu. would you please check it again and let me know as it still persist on your side?

**Comment by liutingdu** [comment]
@affan00 

I think it's happening because I signed in with my Evercam account (You can see from my screenshot, on the bottom left). After logging out, the problem is gone.

**Comment by affan00** [comment]
@liutingdu ok fine thanks.

**Comment by affan00** [comment]
@liutingdu @marcoherbst latest screenshot. 
1.  One scroll bar.
2.  space between text.
3.  Remove Unnecessary divider
4.  Decrease space.
![latest-space](https://cloud.githubusercontent.com/assets/14149453/10789374/e150c6b8-7d9e-11e5-911c-703b53fe13c9.png)

**Comment by marcoherbst** [comment]
the evercam logo is in the wrong place.

On 28 October 2015 at 13:12, Affan Qureshi <notifications@github.com> wrote:

> @liutingdu <https://github.com/liutingdu> @marcoherbst
> <https://github.com/marcoherbst> latest screenshot.
> 1. One scroll bar.
> 2. space between text.
> 3. Remove Unnecessary divider
> 4. Decrease space.
> [image: latest-space]
> <https://cloud.githubusercontent.com/assets/14149453/10789374/e150c6b8-7d9e-11e5-911c-703b53fe13c9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/88#issuecomment-151841474>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst screenshot that liutingdu share is after dragging browser narrower and i share screenshot on full screen. That's why its seems different. else wise if you want to place evercam logo above the snap  on full screen. I will do it.

**Comment by marcoherbst** [comment]
yes do it.

On 28 October 2015 at 13:44, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> screenshot that liutingdu
> share is after dragging browser narrower and i share screenshot on full
> screen. That's why its seems different. else wise if you want to place
> evercam logo above the snap on full screen. I will do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/88#issuecomment-151848444>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst Does this seem fine?
![issue evercam logo](https://cloud.githubusercontent.com/assets/14149453/10817915/27583752-7e5f-11e5-96e1-2944d13f39d8.png)

**Comment by marcoherbst** [comment]
logo align right.
m

On 29 October 2015 at 12:07, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Does this seem fine?
> [image: issue evercam logo]
> <https://cloud.githubusercontent.com/assets/14149453/10817915/27583752-7e5f-11e5-96e1-2944d13f39d8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/88#issuecomment-152158738>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst does this seem fine?
![latest check](https://cloud.githubusercontent.com/assets/14149453/10818242/cbf9ae7e-7e61-11e5-98b7-c84b4fb1b927.png)

**Comment by marcoherbst** [comment]
move it to the right more.

On 29 October 2015 at 12:24, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> does this seem fine?
> [image: latest check]
> <https://cloud.githubusercontent.com/assets/14149453/10818242/cbf9ae7e-7e61-11e5-98b7-c84b4fb1b927.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/88#issuecomment-152162876>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst now?
![icon evercam](https://cloud.githubusercontent.com/assets/14149453/10819856/3e072c3a-7e6c-11e5-9680-905af3130ad5.png)

**Comment by marcoherbst** [comment]
Lovely :)

On 29 October 2015 at 13:39, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> now?
> [image: icon evercam]
> <https://cloud.githubusercontent.com/assets/14149453/10819856/3e072c3a-7e6c-11e5-9680-905af3130ad5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/88#issuecomment-152182006>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
@marcoherbst  oki :)

**Comment by affan00** [comment]
@marcoherbst  public camera UI issue resolved and deployed
