### ISSUE TITLE
Firefox issues on /public/cameras

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#89]
A friend of @vinnieq reported this a few weeks ago. When It's tested & fixed, we'll follow up with him.

**Comment by marcoherbst** [comment]
@affan00  ... could you test the /public/cameras area with Firefox and see if you notice any issues.

**Comment by affan00** [comment]
There is no issue on public/cameras area. Its seems fine on firefox.

**Comment by marcoherbst** [comment]
Ok, good. Tks.
