### ISSUE TITLE
Vendor / Model speed of loading...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#90]
The original idea was to use JS to load this stuff.

The speed is terrible, it either needs to be implemented better or we move to RoR  / PHP server side processing ... or Jekyll type static content generated site.

**Comment by marcoherbst** [comment]
This is an open question as to how to do it.

**Comment by affan00** [comment]
@marcoherbst  ... as php is fast and get stuff done and ruby is extremely flexible and things move quickly, so if we want processing speed fast than should go to php else vice ruby is the best option.

**Comment by marcoherbst** [comment]
Great, do it in PHP as it's a PHP site right now.

**Comment by marcoherbst** [comment]
I'm going to put this on the long finger, it's not important enough.

**Comment by marcoherbst** [comment]
I'm going to close this too ... I think we'll come up with something altogether better, later.
