### ISSUE TITLE
Vendor / Model bring some design from Cambase.io

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#91]
Lots of room to improve this.

**Comment by marcoherbst** [comment]
Step 1: Try to build php equivalents of the cambase pages.

Step 2: Try to build a Jekyll Collection for the cambase pages:
http://jekyllrb.com/docs/collections/

Then let's see which one we prefer :)

M

**Comment by marcoherbst** [comment]
Affan, this is a big task, approach with care.

**Comment by affan00** [comment]
@marcoherbst does this design seem fine? 
![vendors2](https://cloud.githubusercontent.com/assets/14149453/10844990/09cac390-7f26-11e5-99a9-7e7dbbefa447.png)

**Comment by affan00** [comment]
@marcoherbst this is without including nav and footer. Just body section.

**Comment by marcoherbst** [comment]
Better to send me this stuff by email (as this will be a long process) and
better to only send me work that you consider complete with nav, footer,
fonts etc.

M

On 30 October 2015 at 11:51, Affan Qureshi <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> this is without including
> nav and footer. Just body section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-public-site/issues/91#issuecomment-152504858>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
