### ISSUE TITLE
Mobile site isn't working very well. Homepage.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#94]
@azharmalik3  ... not urgent. I've just tagged you so that you could assign this to someone else. Maybe Asim, maybe Affan / Muneeb.

M

**Comment by marcoherbst** [comment]
@affan00  , the task here is to go through the whole site on your mobile and make a note of all the issues you see. Include them in this issue.

**Comment by affan00** [comment]
@marcoherbst ..
1.Image on snapmail, cloud storage, timelapse is not visible (in opera browser) but visible in chrome.
2.In Add your camera session snap of camera  in step1 is not visible properly (in opera browser) but     visible in chrome. 
3.In Requires Authentication hints (create username, camera password) should be in light gray color like http:// hint (external ip/URL)
4.so much gap between ADD A CAMERA link and Apps heading.

**Comment by affan00** [comment]
create new issues with snapshots. Done.
